#!python

import argparse
import sys
import os
import base64

parser = argparse.ArgumentParser(description='js resource packer')
parser.add_argument('inputdir')
parser.add_argument('outputfile')
args = parser.parse_args()
inputdir = args.inputdir
outputfile = args.outputfile

f = open(outputfile, "w", encoding="utf-8")
f.write('''
//
// DOT NOT EDIT IT
// resources file auto generated by pack_res.py
//
''')
f.write("var static_res = {\n")
for file in os.listdir(inputdir):
	with open(inputdir + "/" + file, "rb") as rf:
		b64dat = base64.standard_b64encode(rf.read())
		f.write("'%s':'%s',\n" % (file, b64dat.decode("utf-8")))
f.write("};\n")
